services:
  jt-router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jt-router
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped